In [1]:
import tensorflow as tf

x = tf.constant(0.0, dtype=tf.float32)
y = 2 * x

z = tf.gradients(ys=x+y, xs=[x, y])

init = tf.global_variables_initializer()

with tf.Session() as sess:
    init.run()
    ret = [z[0].eval(), z[1].eval()]

print(ret)

[3.0, 1.0]


In [2]:
x = tf.constant(0.0, dtype=tf.float32)
y = 2 * x

z_fixed = tf.gradients(ys=x+y, xs=[x, y], stop_gradients=[x, y])

with tf.Session() as sess:
    init.run()
    ret_fixed = [z_fixed[0].eval(), z_fixed[1].eval()]

print(ret_fixed)

[1.0, 1.0]


In [3]:
x = tf.stop_gradient(tf.constant(0.0, dtype=tf.float32))
y = tf.stop_gradient(2 * x)

z_fixed = tf.gradients(ys=x+y, xs=[x, y])

with tf.Session() as sess:
    init.run()
    ret_fixed = [z_fixed[0].eval(), z_fixed[1].eval()]

print(ret_fixed)

[1.0, 1.0]


In [4]:
A = tf.placeholder(dtype=tf.float32, shape=(None,3))
B = A + 5

with tf.Session() as sess:
    B_val_1 = B.eval(feed_dict={A: [[1, 2, 3]]})
    B_val_2 = B.eval(feed_dict={A: [[4, 5, 6],
                                    [7, 8, 9]]})

print(B_val_1)
print(B_val_2)

[[6. 7. 8.]]
[[ 9. 10. 11.]
 [12. 13. 14.]]
